#!/bin/csh

#$ -M yding4@nd.edu      # Email address for job notification
#$ -m abe                # Send mail when job begins, ends and aborts
#$ -pe mpi-24 24         # Specify parallel environment and legal core size
#$ -q debug              # Specify queue
#$ -N python_test                # Specify job name

module load python python 2.7.5
module load torch
module load pandas
module load sklearn

python test.py # Application to execute
